### ISSUE TITLE
[Bug] 1.20.1 Fabric - REI: Server failed to synchronize recipe data...

### ISSUE THREAD

**Issue by pewblaze** [SuperMartijn642/Pottery#1] opened 2023-12-31 15:42 UTC
**Version Info**
- Minecraft 1.20.1
- Pottery 1.0.0

**What mod loader are you using?**: Fabric/Forge/NeoForge/Quilt
fabric-api-0.91.0+1.20.1.jar
Loader: 0.15.3

**Description of the Bug**
REI breaks + recipe book breaks with this error in the chat:
`REI: Server failed to synchronize recipe data with the client! Please check the server console log for errors, this breaks REI and vanilla recipe books!`
+
Removing the mod fixes the problem.
Heres also the server log but i dont think that there is anything helpful:
https://gist.github.com/pewblaze/995b4de21a07db129e15146ea11ae528

**Steps to Reproduce**
-

**Screenshots**
-

I think its a comp. issue -> i only found the same bug with Roughly Enough Resources ages ago via google:
https://github.com/theorbtwo/RoughlyEnoughResources/issues/60

Maybe thats related, idk. Wanted to share this if needed and someone else gets this bug :) 
My Pack is selfmade & big so i cant give more input why or which mod could cause this.

**Comment by SuperMartijn642** [comment] 2023-12-31 15:53
Everything seems to work fine and the issue does not occur with just Roughly Enough Items and Pottery. I also don't really see anything related to pottery in the logs.

Are you sure this is caused by Pottery? If so, there's likely some other mod involved too. Could you narrow down the mods needed to reproduce the issue?

**Comment by SuperMartijn642** [comment] 2024-01-05 21:01
Seems someone ran into the same issue in #2.
I found the problem now though, I simply forgot to return the recipe serializer for pot recipes 😅
Still wasn't able to replicate it, so likely just something to do with me testing it in a dev environment.

It should be fixed now in Pottery version 1.0.1.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2024-01-05 21:01 UTC
Labels: bug
